/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libraury_app;

import java.awt.Frame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Victor
 */
public class Admin_login extends javax.swing.JFrame {

    /**
     * Creates new form Admin_login
     */
    public Admin_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        staff_name = new javax.swing.JTextField();
        staff_No = new javax.swing.JPasswordField();
        btm_login = new javax.swing.JButton();
        btm_login1 = new javax.swing.JButton();
        btm_cancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btm_login2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(153, 51, 255));
        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("Please enter your info to login");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 710, 70));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel3.setText("Staff  ID Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 300, 40));

        staff_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_nameActionPerformed(evt);
            }
        });
        getContentPane().add(staff_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 151, 260, 50));
        getContentPane().add(staff_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 253, 260, 50));

        btm_login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btm_login.setText("Login");
        btm_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btm_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 90, 40));

        btm_login1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btm_login1.setText("Reset");
        btm_login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_login1ActionPerformed(evt);
            }
        });
        getContentPane().add(btm_login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 90, 40));

        btm_cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btm_cancel.setText("Cancel");
        btm_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_cancelActionPerformed(evt);
            }
        });
        getContentPane().add(btm_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 90, 40));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel5.setText("Staff Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 220, 50));

        btm_login2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btm_login2.setText("back");
        btm_login2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_login2ActionPerformed(evt);
            }
        });
        getContentPane().add(btm_login2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 90, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff_login.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btm_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_loginActionPerformed
        // TODO add your handling code here:
        try
        {
            Connection con= DriverManager.getConnection("jdbc:derby:Libraury_db","LIB","LIB");
            PreparedStatement pst = con.prepareStatement("SELECT * FROM LOGIN WHERE STAFF_NAME=? and   STAFF_ID=?");
            pst.setString(1, staff_name.getText());
            pst.setString(2, String.valueOf(staff_No.getPassword()));
            ResultSet rs =pst.executeQuery();

            if(rs.next())
            {

                JOptionPane.showMessageDialog(null, "login successfull");
                
                    new admin_user_tabed().setVisible(true);

              
                dispose();

            }else{
                JOptionPane.showMessageDialog(null, "login failed");
            }

        }
        catch(Exception obj)
        {
            obj.printStackTrace();
            JOptionPane.showMessageDialog(null, "database connection failed");

        }
    }//GEN-LAST:event_btm_loginActionPerformed

    private void btm_login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_login1ActionPerformed
        // TODO add your handling code here:
        staff_name.setText("");
        staff_No.setText("");
    }//GEN-LAST:event_btm_login1ActionPerformed

    private void btm_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_cancelActionPerformed
        // TODO add your handling code here:
        Frame fr = new Frame("Exit");
        if(JOptionPane.showConfirmDialog(fr, "Confirm if you want to exit","Login ",JOptionPane.YES_NO_CANCEL_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btm_cancelActionPerformed

    private void staff_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staff_nameActionPerformed

    private void btm_login2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_login2ActionPerformed
        // TODO add your handling code here:
         new Splash_screen().setVisible(true);
                dispose();
    }//GEN-LAST:event_btm_login2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm_cancel;
    private javax.swing.JButton btm_login;
    private javax.swing.JButton btm_login1;
    private javax.swing.JButton btm_login2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField staff_No;
    private javax.swing.JTextField staff_name;
    // End of variables declaration//GEN-END:variables
}
