/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libraury_app;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Victor
 */
public class admin_user_tabed extends javax.swing.JFrame {

    /**
     * Creates new form admin_user_tabed
     */
    public admin_user_tabed() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        insert7 = new javax.swing.JButton();
        delete1 = new javax.swing.JButton();
        update1 = new javax.swing.JButton();
        showbdb = new javax.swing.JButton();
        delete2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        bk_db = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        txt_Name2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_Name4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_Name3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        delete3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_class = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_sem = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        insert = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        show = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        active_students = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_Name1 = new javax.swing.JTextField();
        txt_no2 = new javax.swing.JTextField();
        show2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        st_n = new javax.swing.JTextField();
        st_i = new javax.swing.JTextField();
        bk_n = new javax.swing.JTextField();
        cancel_bk = new javax.swing.JButton();
        issue_bk = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        bk_id = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        ised_bks = new javax.swing.JTable();
        bk_showi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        st_n1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        st_i1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        bk_n1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        bk_i1 = new javax.swing.JTextField();
        cancel_bk_re = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        rtd_bks1 = new javax.swing.JTable();
        bk_showi1 = new javax.swing.JButton();
        btm_return1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        insert4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ebooks_txtarea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane4.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane4.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane4.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane4.setAlignmentX(0.0F);
        jTabbedPane4.setAlignmentY(0.0F);
        jTabbedPane4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jTabbedPane4.setMaximumSize(new java.awt.Dimension(32900, 32900));
        jTabbedPane4.setOpaque(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true), "Table Actions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 18))); // NOI18N
        jPanel6.setOpaque(false);

        insert7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        insert7.setText("insert ");
        insert7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert7ActionPerformed(evt);
            }
        });

        delete1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        delete1.setText("delete");
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });

        update1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        update1.setText("Update");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });

        showbdb.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        showbdb.setText("Show");
        showbdb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showbdbMouseClicked(evt);
            }
        });
        showbdb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbdbActionPerformed(evt);
            }
        });

        delete2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        delete2.setText("Cancel");
        delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(update1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insert7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(delete1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showbdb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insert7)
                            .addComponent(delete1))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(update1)
                            .addComponent(showbdb)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(delete2)))
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 320, 150));

        bk_db.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Id", "Book Name", "Author"
            }
        ));
        bk_db.setOpaque(false);
        bk_db.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bk_dbMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(bk_db);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, 510));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true), "Book Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 18), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(txt_Name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 238, 230, 30));

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("Book Author");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 192, 180, 40));

        txt_Name4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Name4ActionPerformed(evt);
            }
        });
        jPanel7.add(txt_Name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 148, 230, 30));

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("Book ID");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 102, 180, 40));
        jPanel7.add(txt_Name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 66, 230, 30));

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("Book Name");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, 40));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 320, 290));

        delete3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        delete3.setText("back");
        delete3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete3ActionPerformed(evt);
            }
        });
        jPanel1.add(delete3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 880, 590));

        jTabbedPane4.addTab("book database", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Student Class");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 180, 50));
        jPanel2.add(txt_class, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 180, 40));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8.setText("Student Semester");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 190, 50));

        txt_sem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_semActionPerformed(evt);
            }
        });
        jPanel2.add(txt_sem, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 180, 40));

        jLabel9.setBackground(new java.awt.Color(153, 51, 255));
        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Use to update student database");
        jLabel9.setToolTipText("");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 570, 50));

        insert.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        insert.setText("insert ");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        jPanel2.add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 90, 40));

        delete.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel2.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 90, 40));

        update.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel2.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 100, 40));

        show.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        show.setText("Show");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        jPanel2.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 100, 40));

        active_students.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "Student class", "Student semester"
            }
        ));
        active_students.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                active_studentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(active_students);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 870, 210));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("Student Name");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 50));

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 51));
        jLabel11.setText("Student Number");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 190, 50));
        jPanel2.add(txt_Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 230, 40));

        txt_no2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_no2ActionPerformed(evt);
            }
        });
        jPanel2.add(txt_no2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 230, 40));

        show2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        show2.setText("Cancel");
        show2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show2ActionPerformed(evt);
            }
        });
        jPanel2.add(show2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, 100, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(700, 578));
        jLabel3.setMinimumSize(new java.awt.Dimension(700, 578));
        jLabel3.setPreferredSize(new java.awt.Dimension(700, 578));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 560));

        jTabbedPane4.addTab("Student database", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 0));
        jLabel17.setText("Student Name");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, 40));

        jLabel18.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 0));
        jLabel18.setText("Student id");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 160, 50));

        jLabel19.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 0));
        jLabel19.setText("Book Name");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 170, 50));

        st_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_nActionPerformed(evt);
            }
        });
        jPanel3.add(st_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 190, 40));

        st_i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_iActionPerformed(evt);
            }
        });
        jPanel3.add(st_i, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 190, 40));

        bk_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bk_nActionPerformed(evt);
            }
        });
        jPanel3.add(bk_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 190, 40));

        cancel_bk.setBackground(new java.awt.Color(204, 204, 204));
        cancel_bk.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        cancel_bk.setText("Cancel book issue ");
        cancel_bk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_bkActionPerformed(evt);
            }
        });
        jPanel3.add(cancel_bk, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 210, 50));

        issue_bk.setBackground(new java.awt.Color(204, 204, 204));
        issue_bk.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        issue_bk.setText("issue book");
        issue_bk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issue_bkActionPerformed(evt);
            }
        });
        jPanel3.add(issue_bk, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 170, 50));

        jLabel20.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 0));
        jLabel20.setText("Book id");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 150, 50));

        bk_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bk_idActionPerformed(evt);
            }
        });
        jPanel3.add(bk_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 190, 40));

        ised_bks.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        ised_bks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "Student ID", "Book Name", "Book ID"
            }
        ));
        ised_bks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ised_bksMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(ised_bks);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 360, 260));

        bk_showi.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        bk_showi.setText("Show issed books");
        bk_showi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bk_showiActionPerformed(evt);
            }
        });
        jPanel3.add(bk_showi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 190, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 970, 580));

        jTabbedPane4.addTab("Issue Book", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 0));
        jLabel21.setText("Student Name");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, 40));

        st_n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_n1ActionPerformed(evt);
            }
        });
        jPanel4.add(st_n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 180, 40));

        jLabel22.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 0));
        jLabel22.setText("Student id");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 160, 50));

        st_i1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_i1ActionPerformed(evt);
            }
        });
        jPanel4.add(st_i1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 180, 40));

        jLabel23.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 0));
        jLabel23.setText("Book Name");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 170, 50));

        bk_n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bk_n1ActionPerformed(evt);
            }
        });
        jPanel4.add(bk_n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 180, 40));

        jLabel24.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 0));
        jLabel24.setText("Book id");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 150, 50));

        bk_i1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bk_i1ActionPerformed(evt);
            }
        });
        jPanel4.add(bk_i1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 180, 40));

        cancel_bk_re.setBackground(new java.awt.Color(204, 204, 204));
        cancel_bk_re.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        cancel_bk_re.setText("Cancel book return ");
        cancel_bk_re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_bk_reActionPerformed(evt);
            }
        });
        jPanel4.add(cancel_bk_re, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 210, 50));

        rtd_bks1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        rtd_bks1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "Student ID", "Book Name", "Book ID"
            }
        ));
        rtd_bks1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rtd_bks1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(rtd_bks1);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 410, 310));

        bk_showi1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        bk_showi1.setText("Show returned books");
        bk_showi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bk_showi1MouseClicked(evt);
            }
        });
        bk_showi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bk_showi1ActionPerformed(evt);
            }
        });
        jPanel4.add(bk_showi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 230, 50));

        btm_return1.setBackground(new java.awt.Color(204, 204, 204));
        btm_return1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btm_return1.setText("return  book");
        btm_return1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btm_return1MouseClicked(evt);
            }
        });
        btm_return1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_return1ActionPerformed(evt);
            }
        });
        jPanel4.add(btm_return1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 160, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 570));

        jTabbedPane4.addTab("Return Book", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insert4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        insert4.setText("click to edit or read a book in the ebook libraury");
        insert4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert4ActionPerformed(evt);
            }
        });
        jPanel5.add(insert4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 60));

        ebooks_txtarea.setColumns(20);
        ebooks_txtarea.setRows(5);
        ebooks_txtarea.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(204, 51, 0)));
        jScrollPane3.setViewportView(ebooks_txtarea);
        ebooks_txtarea.getAccessibleContext().setAccessibleParent(jTabbedPane4);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 780, 400));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 530));

        jTabbedPane4.addTab("Ebooks", jPanel5);

        getContentPane().add(jTabbedPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 530));
        jTabbedPane4.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_semActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_semActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_semActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:derby:Libraury_db","LIB","LIB");
            PreparedStatement pst = con.prepareStatement("insert into STUDENTS_MASTER values (?,?,?,?)");

            pst.setInt(1, Integer.valueOf(txt_no2.getText()));
            pst.setString(2, txt_Name1.getText());
            pst.setString(3, txt_class.getText());
            pst.setString(4, txt_sem.getText());

            int i;
            i = pst.executeUpdate();
            if (i > 0) {

                JOptionPane.showMessageDialog(null, "Inserted new student successfully");

            }
        } catch (Exception obj) {
            obj.getStackTrace();
            JOptionPane.showMessageDialog(null, obj);
            
        }
    }//GEN-LAST:event_insertActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:derby:Libraury_db","LIB","LIB");
            PreparedStatement pst = con.prepareStatement("delete from STUDENTS_MASTER where STD_ID=?");
            pst.setInt(1, Integer.valueOf(txt_no2.getText()));
            int i = pst.executeUpdate();
            if (i > 0) {

                JOptionPane.showMessageDialog(null, "deleted student successfull");
            }

        } catch (Exception obj) {
            obj.getStackTrace();
            JOptionPane.showMessageDialog(null, obj);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:derby:Libraury_db","LIB","LIB");
            PreparedStatement pst = con.prepareStatement(" update  STUDENTS_MASTER set STD_NAME=?,STD_CLASS=?,STD_SEM=? where STD_ID=?");
            pst.setInt(4, Integer.valueOf(txt_no2.getText()));
            pst.setString(1, txt_Name1.getText());
            pst.setString(2, txt_class.getText());
            pst.setString(3, txt_sem.getText());
            int i = pst.executeUpdate();
            if (i > 0) {

                JOptionPane.showMessageDialog(null, "Updated student database successfull");
            }

        } catch (Exception obj) {
            obj.getStackTrace();
            JOptionPane.showMessageDialog(null, obj);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:derby:Libraury_db","LIB","LIB");
            PreparedStatement pst = con.prepareStatement("select * from STUDENTS_MASTER ");

            ResultSet re = pst.executeQuery();
            DefaultTableModel dtm = (DefaultTableModel) active_students.getModel();
            dtm.setRowCount(0);
            while (re.next()) {
                Integer STD_I = re.getInt("STD_ID");
                String STD_NAM = re.getString("STD_NAME");
                String STD_CLAS = re.getString("STD_CLASS");
                String STD_SE = re.getString("STD_SEM");
                dtm.addRow(new Object[]{STD_I, STD_NAM, STD_CLAS, STD_SE});

            }
        } catch (Exception obj) {
            obj.getStackTrace();
            JOptionPane.showMessageDialog(null, obj);
        }

    }//GEN-LAST:event_showActionPerformed

    private void st_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st_nActionPerformed

    private void st_iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_iActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st_iActionPerformed

    private void bk_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bk_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bk_nActionPerformed

    private void cancel_bkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_bkActionPerformed
        // TODO add your handling code here:
        st_n.setText("");
        st_i.setText("");
        bk_n.setText("");
        bk_id.setText("");
    }//GEN-LAST:event_cancel_bkActionPerformed

    private void issue_bkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issue_bkActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:derby:Libraury_db","LIB","LIB");
            PreparedStatement pst = con.prepareStatement("insert into ISSUE values (?,?,?,?)");

            pst.setString(1, st_n.getText());
            pst.setInt(2, Integer.valueOf(st_i.getText()));
            pst.setString(3, bk_n.getText());
            pst.setInt(4, Integer.valueOf(bk_id.getText()));

            int i = pst.executeUpdate();
            if (i > 0) {

                JOptionPane.showMessageDialog(null,bk_n.getText()+ "issued  successfully");
            }
        } catch (Exception obj) {
            obj.getStackTrace();
              JOptionPane.showMessageDialog(null,bk_n.getText()+ "Book issue not successfull. ");
            
        }
    }//GEN-LAST:event_issue_bkActionPerformed

    private void st_n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_n1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st_n1ActionPerformed

    private void st_i1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_i1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st_i1ActionPerformed

    private void bk_n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bk_n1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bk_n1ActionPerformed

    private void bk_i1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bk_i1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bk_i1ActionPerformed

    private void cancel_bk_reActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_bk_reActionPerformed
        // TODO add your handling code here:
        st_n.setText("");
        st_i.setText("");
        bk_n.setText("");
        bk_id.setText("");
    }//GEN-LAST:event_cancel_bk_reActionPerformed

    private void bk_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bk_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bk_idActionPerformed

    private void txt_no2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_no2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_no2ActionPerformed

    private void insert4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert4ActionPerformed
        // TODO add your handling code here:

        JFileChooser fc = new JFileChooser("C:\\Users\\Victor\\Desktop\\javawork\\Libraury_App\\ebooks");
        fc.showOpenDialog(null);
        File f = fc.getSelectedFile();
        String filename = f.getAbsolutePath();
        try {

            FileReader reader = new FileReader(filename);
            try (BufferedReader br = new BufferedReader(reader)) {
                ebooks_txtarea.read(br, null);
            }
            ebooks_txtarea.requestFocus();

        } catch (Exception e) {
            e.getStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_insert4ActionPerformed

    private void active_studentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_active_studentsMouseClicked
        // TODO add your handling code here:
        int selectedRow = active_students.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) active_students.getModel();

        try {
            txt_no2.setText(model.getValueAt(selectedRow, 0).toString());
            txt_Name1.setText(model.getValueAt(selectedRow, 1).toString());
            txt_class.setText(model.getValueAt(selectedRow, 2).toString());
            txt_sem.setText(model.getValueAt(selectedRow, 3).toString());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_active_studentsMouseClicked

    private void insert7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert7ActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:derby:Libraury_db","LIB","LIB");
            PreparedStatement pst = con.prepareStatement("insert into BOOKS values (?,?,?)");

            pst.setInt(1, Integer.valueOf(txt_Name4.getText()));
            pst.setString(2, txt_Name3.getText());
            pst.setString(3, txt_Name2.getText());

            int i;
            i = pst.executeUpdate();
            if (i > 0) {

                JOptionPane.showMessageDialog(null, "Inserted new BOOK successfully");

            }
        } catch (Exception obj) {
            obj.getStackTrace();
        }

    }//GEN-LAST:event_insert7ActionPerformed

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:derby:Libraury_db","LIB","LIB");
            PreparedStatement pst = con.prepareStatement("delete from BOOKS where BOOK_ID=?");
            pst.setInt(1, Integer.valueOf(txt_Name4.getText()));
            int i = pst.executeUpdate();
            if (i > 0) {

                JOptionPane.showMessageDialog(null, "deleted BOOK successfull");
            }

        } catch (Exception obj) {
            obj.getStackTrace();
        }
    }//GEN-LAST:event_delete1ActionPerformed

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:derby:Libraury_db","LIB","LIB");
            PreparedStatement pst = con.prepareStatement("update  BOOKS set BOOK_NAME=?,AUTHOR=? where BOOK_ID=?");
            pst.setInt(3, Integer.valueOf(txt_Name4.getText()));
            pst.setString(1, txt_Name3.getText());
            pst.setString(2, txt_Name2.getText());
            int i = pst.executeUpdate();
            if (i > 0) {

                JOptionPane.showMessageDialog(null, "Updated BOOKS database successfull");
            }

        } catch (Exception obj) {
            obj.getStackTrace();
              JOptionPane.showMessageDialog(null, obj);
        }
    }//GEN-LAST:event_update1ActionPerformed

    private void showbdbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbdbActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:derby:Libraury_db","LIB","LIB");
            PreparedStatement pst = con.prepareStatement("select * from BOOKS ");

            ResultSet re = pst.executeQuery();
            DefaultTableModel dtm = (DefaultTableModel) bk_db.getModel();
            dtm.setRowCount(0);
            while (re.next()) {
                Integer STD_I = re.getInt("BOOK_ID");
                String STD_NAM = re.getString("BOOK_NAME");
                String STD_CLAS = re.getString("AUTHOR");

                dtm.addRow(new Object[]{STD_I, STD_NAM, STD_CLAS,});

            }
        } catch (Exception obj) {
            obj.getStackTrace();
             JOptionPane.showMessageDialog(null, "an error occured");
        }
    }//GEN-LAST:event_showbdbActionPerformed

    private void txt_Name4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Name4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Name4ActionPerformed

    private void bk_dbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bk_dbMouseClicked
        // TODO add your handling code here:
       int selectedRow = bk_db.getSelectedRow();
       DefaultTableModel model = (DefaultTableModel) bk_db.getModel();

        try {
         txt_Name4.setText(model.getValueAt(selectedRow, 0).toString());
         txt_Name3.setText(model.getValueAt(selectedRow, 1).toString());
         txt_Name2.setText(model.getValueAt(selectedRow, 2).toString());
        

     } catch (Exception e) {
         JOptionPane.showMessageDialog(null, e);
       }

    }//GEN-LAST:event_bk_dbMouseClicked

    private void delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete2ActionPerformed
        // TODO add your handling code here:
        txt_Name3.setText("");
        txt_Name4.setText("");
        txt_Name2.setText("");
    }//GEN-LAST:event_delete2ActionPerformed

    private void show2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show2ActionPerformed
        // TODO add your handling code here:
        txt_Name1.setText("");
        txt_no2.setText("");
        txt_class.setText("");
        txt_sem.setText("");
    }//GEN-LAST:event_show2ActionPerformed

    private void delete3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete3ActionPerformed
        // TODO add your handling code here:
          new Admin_login().setVisible(true);
                dispose();
    }//GEN-LAST:event_delete3ActionPerformed

    private void ised_bksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ised_bksMouseClicked
        // TODO add your handling code here:
           int selectedRow = ised_bks.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) ised_bks.getModel();

        try {
            st_n.setText(model.getValueAt(selectedRow, 0).toString());
            st_i.setText(model.getValueAt(selectedRow, 1).toString());
            bk_n.setText(model.getValueAt(selectedRow, 2).toString());
            bk_id.setText(model.getValueAt(selectedRow, 3).toString());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ised_bksMouseClicked

    private void bk_showiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bk_showiActionPerformed
        // TODO add your handling code here:
           try {
            Connection con = DriverManager.getConnection("jdbc:derby:Libraury_db","LIB","LIB");
            PreparedStatement pst = con.prepareStatement("select * from ISSUE ");

            ResultSet re = pst.executeQuery();
            DefaultTableModel dtm = (DefaultTableModel) ised_bks.getModel();
            dtm.setRowCount(0);
            while (re.next()) {
             
                String st_n = re.getString("STUDENT_NAME");
                Integer st_i = re.getInt("STUDENT_ID");
                String bk_n = re.getString("BOOK_NAME");
                Integer bk_id = re.getInt("BOOK_ID");
                dtm.addRow(new Object[]{st_n, st_i, bk_n,bk_id});

                
                
            }
        } catch (Exception obj) {
            obj.getStackTrace();
            // JOptionPane.showMessageDialog(null, "An error occured");
        }
    }//GEN-LAST:event_bk_showiActionPerformed

    private void showbdbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showbdbMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_showbdbMouseClicked

    private void rtd_bks1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rtd_bks1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rtd_bks1MouseClicked

    private void bk_showi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bk_showi1ActionPerformed
        try {
            Connection con = DriverManager.getConnection("jdbc:derby:Libraury_db","LIB","LIB");
            PreparedStatement pst = con.prepareStatement("select * from STUDENTS_WITHBOOKS ");

            ResultSet re = pst.executeQuery();
            DefaultTableModel dtm = (DefaultTableModel) rtd_bks1.getModel();
            dtm.setRowCount(0);
            while (re.next()) {
             
                String st_n = re.getString("STUDENT_NAME");
                Integer st_i = re.getInt("STUDNT_ID");
                 Integer bk_id = re.getInt("BOOK_ID");
                String bk_n = re.getString("BOOK_NAME");
                dtm.addRow(new Object[]{st_n, st_i, bk_n,bk_id});

                
                
            }
        } catch (Exception obj) {
            obj.getStackTrace();
           // JOptionPane.showMessageDialog(null, "An error occured");
        }        
        
        
        
        
    }//GEN-LAST:event_bk_showi1ActionPerformed

    private void bk_showi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bk_showi1MouseClicked
        
                  try {
            Connection con = DriverManager.getConnection("jdbc:derby:Libraury_db","LIB","LIB");
            PreparedStatement pst = con.prepareStatement("select * from STUDENTS_WITHBOOKS ");

            ResultSet re = pst.executeQuery();
            DefaultTableModel dtm = (DefaultTableModel) rtd_bks1.getModel();
            dtm.setRowCount(0);
            while (re.next()) {
             
                String st_n1 = re.getString("STUDENT_NAME");
                Integer st_i1 = re.getInt("STUDNT_ID");
                String bk_n1 = re.getString("BOOK_NAME");
                Integer bk_id1 = re.getInt("BOOK_ID");
                dtm.addRow(new Object[]{st_n1, st_i1, bk_n1,bk_id1});

                            
            }
        } catch (Exception obj) {
            obj.getStackTrace();
             JOptionPane.showMessageDialog(null, "An error occured");
        }
    }//GEN-LAST:event_bk_showi1MouseClicked

    private void btm_return1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btm_return1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btm_return1MouseClicked

    private void btm_return1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_return1ActionPerformed
        // TODO add your handling code here:
              try {
            Connection con = DriverManager.getConnection("jdbc:derby:Libraury_db","LIB","LIB");
            PreparedStatement pst = con.prepareStatement("delete from ISSUE where STUDENT_ID=?");
            pst.setInt(1, Integer.valueOf(st_i1.getText()));
            
            int i = pst.executeUpdate();
            if (i > 0) {
                

                JOptionPane.showMessageDialog(null, bk_n.getText()+" returned successfully");
            }
        } catch (Exception obj) {
            obj.getStackTrace();
             JOptionPane.showMessageDialog(null, bk_n.getText()+"Book return not sccessfull. ");
        }
    }//GEN-LAST:event_btm_return1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_user_tabed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_user_tabed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_user_tabed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_user_tabed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_user_tabed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable active_students;
    private javax.swing.JTable bk_db;
    private javax.swing.JTextField bk_i1;
    private javax.swing.JTextField bk_id;
    private javax.swing.JTextField bk_n;
    private javax.swing.JTextField bk_n1;
    private javax.swing.JButton bk_showi;
    private javax.swing.JButton bk_showi1;
    private javax.swing.JButton btm_return1;
    private javax.swing.JButton cancel_bk;
    private javax.swing.JButton cancel_bk_re;
    private javax.swing.JButton delete;
    private javax.swing.JButton delete1;
    private javax.swing.JButton delete2;
    private javax.swing.JButton delete3;
    private javax.swing.JTextArea ebooks_txtarea;
    private javax.swing.JButton insert;
    private javax.swing.JButton insert4;
    private javax.swing.JButton insert7;
    private javax.swing.JTable ised_bks;
    private javax.swing.JButton issue_bk;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable rtd_bks1;
    private javax.swing.JButton show;
    private javax.swing.JButton show2;
    private javax.swing.JButton showbdb;
    private javax.swing.JTextField st_i;
    private javax.swing.JTextField st_i1;
    private javax.swing.JTextField st_n;
    private javax.swing.JTextField st_n1;
    private javax.swing.JTextField txt_Name1;
    private javax.swing.JTextField txt_Name2;
    private javax.swing.JTextField txt_Name3;
    private javax.swing.JTextField txt_Name4;
    private javax.swing.JTextField txt_class;
    private javax.swing.JTextField txt_no2;
    private javax.swing.JTextField txt_sem;
    private javax.swing.JButton update;
    private javax.swing.JButton update1;
    // End of variables declaration//GEN-END:variables
}
