/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libraury_app;

import javax.swing.JFrame;
import javax.swing.JOptionPane;



/**
 *
 * @author Victor
 */
public class Splash_screen extends javax.swing.JFrame {

    /**
     * Creates new form Splash_screen
     */
    public Splash_screen() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btmContinue = new javax.swing.JButton();
        btmContinue1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        image = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(153, 51, 255));
        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Login as ");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 230, 70));

        btmContinue.setBackground(new java.awt.Color(102, 102, 102));
        btmContinue.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btmContinue.setText(" staff ");
        btmContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmContinueActionPerformed(evt);
            }
        });
        getContentPane().add(btmContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 120, 50));

        btmContinue1.setBackground(new java.awt.Color(102, 102, 102));
        btmContinue1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btmContinue1.setText("student");
        btmContinue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmContinue1ActionPerformed(evt);
            }
        });
        getContentPane().add(btmContinue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 120, 50));

        jLabel3.setBackground(new java.awt.Color(153, 51, 255));
        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Welcome To The School ELibrary");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 70));
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 240, 40));

        image.setBackground(new java.awt.Color(102, 0, 204));
        image.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin_user_backdrop.jpg"))); // NOI18N
        image.setRequestFocusEnabled(false);
        getContentPane().add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 740, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //main
   
    
    //end of main
    
    private void btmContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmContinueActionPerformed
        // TODO add your handling code here:
          new Admin_login().setVisible(true);
    }//GEN-LAST:event_btmContinueActionPerformed

    private void btmContinue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmContinue1ActionPerformed
        // TODO add your handling code here:
         new student_lib_login().setVisible(true);
         
    }//GEN-LAST:event_btmContinue1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
           Splash_screen splash = new Splash_screen();
            splash.setVisible(true);
           splash.show();
           splash.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       
        
        try {
            for(int i=0;i<=100;i++){
            Thread.sleep(70);
            splash.jProgressBar1.setValue(i);
            if(i==100){
            splash.setVisible(true);
              JOptionPane.showMessageDialog(null, "Please select if your a student or a Staff Member.");
        
            }
            }
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash_screen().setVisible(false);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmContinue;
    private javax.swing.JButton btmContinue1;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
