/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Victor
 */
import java.awt.Frame;
import java.sql.*;
import javax.swing.JOptionPane;
public class login_form extends javax.swing.JFrame {

    /**
     * Creates new form login_form
     */
    public login_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        staff_name = new javax.swing.JTextField();
        staff_No = new javax.swing.JPasswordField();
        btm_login = new javax.swing.JButton();
        btm_cancel = new javax.swing.JButton();
        btm_login1 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Staff Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 138, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Staff Number");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 182, 138, 40));
        jPanel1.add(staff_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 124, 163, 31));
        jPanel1.add(staff_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 182, 163, 33));

        btm_login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btm_login.setText("Login");
        btm_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_loginActionPerformed(evt);
            }
        });
        jPanel1.add(btm_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 276, 90, 40));

        btm_cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btm_cancel.setText("Cancel");
        btm_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(btm_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 276, 90, 40));

        btm_login1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btm_login1.setText("Reset");
        btm_login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_login1ActionPerformed(evt);
            }
        });
        jPanel1.add(btm_login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 276, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btm_login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_login1ActionPerformed
        // TODO add your handling code here:
        staff_name.setText("");
        staff_No.setText("");

    }//GEN-LAST:event_btm_login1ActionPerformed

    private void btm_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_cancelActionPerformed
        // TODO add your handling code here:
        Frame fr = new Frame("Exit");
        if(JOptionPane.showConfirmDialog(fr, "Confirm if you want to exit","Login ",JOptionPane.YES_NO_CANCEL_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btm_cancelActionPerformed

    private void btm_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_loginActionPerformed
        // TODO add your handling code here:
        try
        {
            Connection con= DriverManager.getConnection("jdbc:derby://localhost:1527/Libraurydb","Mosesdb","admin");
            PreparedStatement pst = con.prepareStatement("SELECT * FROM login WHERE EMAIL=? and   PASSWORD=?");
            pst.setString(1, staff_name.getText());
            pst.setString(2, String.valueOf(staff_No.getPassword()));
            ResultSet rs =pst.executeQuery();

            if(rs.next())
            {

                JOptionPane.showMessageDialog(null, "login successfull");
                if(staff_name.getText().equals("Admin"))
                {
                    new admin_page().setVisible(true);

                }
                else
                {
                    new student_form().setVisible(true);

                }
                dispose();

            }else{
                JOptionPane.showMessageDialog(null, "login failed");
            }

        }
        catch(Exception obj)
        {
            obj.printStackTrace();

        }

    }//GEN-LAST:event_btm_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm_cancel;
    private javax.swing.JButton btm_login;
    private javax.swing.JButton btm_login1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPasswordField staff_No;
    private javax.swing.JTextField staff_name;
    // End of variables declaration//GEN-END:variables
}
